//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela
    {
        public int ID { get; set; }
        public double Potrosnja { get; set; }
        public System.DateTime VremeProracuna { get; set; }
        public Nullable<System.DateTime> PoslednjeVremeMerenja { get; set; }
        public string Grad { get; set; }
        public string Funkcija { get; set; }
    }
}
